version: "3.9"

services:
  # api:
  #   container_name: fastify-boilerplate-api
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   command: yarn start:prod
  #   depends_on:
  #     - database
  #   ports:
  #     - "${API_PORT}:${API_PORT}"

  database:
    container_name: ${DATABASE_NAME}
    image: postgres:latest
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:5432
